before:
  hooks:
    - go mod tidy
    - go generate ./...
builds:
  - main: ./cmd/binance-proxy
    env:
      - CGO_ENABLED=0
    goos:
      - linux
      - windows
      - darwin
    goarch:
      - amd64
      - arm
      - arm64
archives:
  - replacements:
      darwin: Darwin
      linux: Linux
      windows: Windows
      amd64: x86_64
checksum:
  name_template: 'checksums.txt'
snapshot:
  name_template: "{{ incpatch .Version }}-next"
changelog:
  sort: asc
  filters:
    exclude:
      - '^docs:'
      - '^test:'

dockers:
- 
  image_templates: ["docker.io/nightshift2k/{{ .ProjectName }}:{{ .Version }}-amd64"]
  dockerfile: Dockerfile
  use: buildx
  build_flag_templates:
  - --platform=linux/amd64
  - --label=org.opencontainers.image.title={{ .ProjectName }}
  - --label=org.opencontainers.image.description={{ .ProjectName }}
  - --label=org.opencontainers.image.url=https://github.com/nightshift2k/{{ .ProjectName }}
  - --label=org.opencontainers.image.source=https://github.com/nightshift2k/{{ .ProjectName }}
  - --label=org.opencontainers.image.version={{ .Version }}
  - --label=org.opencontainers.image.created={{ time "2006-01-02T15:04:05Z07:00" }}
  - --label=org.opencontainers.image.revision={{ .FullCommit }}
  - --label=org.opencontainers.image.licenses=MIT
- 
  image_templates: ["docker.io/nightshift2k/{{ .ProjectName }}:{{ .Version }}-arm64v8"]
  goarch: arm64
  dockerfile: Dockerfile
  use: buildx
  build_flag_templates:
  - --platform=linux/arm64/v8
  - --label=org.opencontainers.image.title={{ .ProjectName }}
  - --label=org.opencontainers.image.description={{ .ProjectName }}
  - --label=org.opencontainers.image.url=https://github.com/nightshift2k/{{ .ProjectName }}
  - --label=org.opencontainers.image.source=https://github.com/nightshift2k/{{ .ProjectName }}
  - --label=org.opencontainers.image.version={{ .Version }}
  - --label=org.opencontainers.image.created={{ time "2006-01-02T15:04:05Z07:00" }}
  - --label=org.opencontainers.image.revision={{ .FullCommit }}
  - --label=org.opencontainers.image.licenses=MIT
docker_manifests:
- name_template: docker.io/nightshift2k/{{ .ProjectName }}:{{ .Version }}
  image_templates:
  - docker.io/nightshift2k/{{ .ProjectName }}:{{ .Version }}-amd64
  - docker.io/nightshift2k/{{ .ProjectName }}:{{ .Version }}-arm64v8
- name_template: docker.io/nightshift2k/{{ .ProjectName }}:latest
  image_templates:
  - docker.io/nightshift2k/{{ .ProjectName }}:{{ .Version }}-amd64
  - docker.io/nightshift2k/{{ .ProjectName }}:{{ .Version }}-arm64v8      